### ISSUE TITLE
太好了，谢谢您，正需要这个

### ISSUE THREAD

**Issue by alwayswdc** [yishanhe/scholar-pac#1]
希望您能持续更新，我也乐意帮忙

**Comment by alwayswdc** [comment]
再看了一下内容，哎，有点寒碜，比较不完善，自己已经fork了。

**Comment by yishanhe** [comment]
@wdc63 不好意思，确实是一个很简单的东西。 help yourself。谢谢啦！弄一个bootstrap简化设置是目前最需要的。毕竟整套设置下来还是很花费时间的。
